name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: copy yml file
      run: |
        echo "${{ secrets.APPLICATION_YML }}" > ./platform-back/src/main/resources/application.yml

    - name: Build with Gradle Wrapper
      run: |
        cd platform-back
        chmod +x gradlew
        export JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} 
        ./gradlew clean --stacktrace --info build

    - name: Upload test reports as artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: build/reports/tests